// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250723150804_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Domain.Entities.Allee", b =>
                {
                    b.Property<int>("AlleeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Allee_Id")
                        .HasComment("Identifiant unique pour chaque Allee.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlleeId"), 1L, 1);

                    b.Property<string>("AlleeNom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Allee_Nom")
                        .HasComment("Nom de l'Allee");

                    b.Property<int?>("AlleeZoneId")
                        .HasColumnType("int")
                        .HasColumnName("Allee_ZoneId")
                        .HasComment("Référence à l'identifiant de la zone à laquelle l'Allee appartient. C'est une clé étrangère.");

                    b.Property<int?>("CodeBarreZoneZoneId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("AlleeId")
                        .HasName("PK__Allee__58D55A03052B8413");

                    b.HasIndex("AlleeZoneId");

                    b.HasIndex("CodeBarreZoneZoneId");

                    b.ToTable("Allee", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_Id")
                        .HasComment("Identifiant unique pour chaque client");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("client_Adress")
                        .HasComment("Adresse physique du client");

                    b.Property<DateTime>("ClientDateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("client_DateCreation")
                        .HasComment("Date de création du client dans le système");

                    b.Property<DateTime?>("ClientDateInactif")
                        .HasColumnType("datetime2")
                        .HasColumnName("client_DateInactif")
                        .HasComment("Date à partir de laquelle le client est devenu inactif");

                    b.Property<string>("ClientNom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("client_Nom")
                        .HasComment("Nom du client");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("client_Email")
                        .HasComment("Adresse e-mail du client");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("client_IsActive")
                        .HasComment("Indique si le client est actif (1 = actif, 0 = inactif)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("client_Telephone")
                        .HasComment("Numéro de téléphone du client");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Client_AspNetUsersId");

                    b.HasKey("ClientId")
                        .HasName("PK__Client__BF554B6CE4B28D07");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ__Client__A7A650D3FAE098F8")
                        .IsUnique();

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreAllee", b =>
                {
                    b.Property<int>("CodeBarreAlleeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreAllee_Id")
                        .HasComment("Identifiant unique pour chaque association entre un code-barres et une Allee.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeBarreAlleeId"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CodeBarreAlleeAlleeId")
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreAllee_AlleeId")
                        .HasComment("Référence à l'identifiant de l'Allee avec ce code-barres est situé. C'est une clé étrangère.");

                    b.HasKey("CodeBarreAlleeId")
                        .HasName("PK__CodeBarr__3A7C90A2A4168A7F");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("CodeBarreAlleeAlleeId");

                    b.ToTable("CodeBarreAllee", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreEtage", b =>
                {
                    b.Property<int>("CodeBarreEtageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreEtage_Id")
                        .HasComment("Identifiant unique pour chaque association entre un code-barres et un étage.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeBarreEtageId"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CodeBarreEtageEtageId")
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreEtage_EtageId")
                        .HasComment("Référence à l'identifiant de l'étage avec ce code-barres est situé. C'est une clé étrangère.");

                    b.Property<int>("Etage")
                        .HasColumnType("int");

                    b.HasKey("CodeBarreEtageId")
                        .HasName("PK__CodeBarr__EC532EC1B8307F25");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("CodeBarreEtageEtageId");

                    b.ToTable("CodeBarreEtage", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreOperateur", b =>
                {
                    b.Property<int>("CodeBarreOperateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreOperateur_Id")
                        .HasComment("Identifiant unique pour chaque association entre un opérateur et un code-barres.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeBarreOperateurId"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CodeBarreOperateurOperateurId")
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreOperateur_OperateurId")
                        .HasComment("Référence à l'identifiant de l'opérateur, lié à la table Operateur.");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("CodeBarreOperateurId")
                        .HasName("PK__CodeBarr__9C140E7C2F7FFFC2");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("CodeBarreOperateurOperateurId");

                    b.HasIndex("SiteId");

                    b.ToTable("CodeBarreOperateur", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreRack", b =>
                {
                    b.Property<int>("CodeBarreRackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreRack_Id")
                        .HasComment("Identifiant unique pour chaque association entre un code-barres et un rack.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeBarreRackId"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CodeBarreRackRackId")
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreRack_RackId")
                        .HasComment("Référence à l'identifiant du rack avec ce code-barres est situé. C'est une clé étrangère.");

                    b.HasKey("CodeBarreRackId")
                        .HasName("PK__CodeBarr__4A88C0C48D7878BA");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("CodeBarreRackRackId");

                    b.ToTable("CodeBarreRack", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreRangee", b =>
                {
                    b.Property<int>("CodeBarreRangéeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreRangée_Id")
                        .HasComment("Identifiant unique pour chaque association entre un code-barres et une rangée.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeBarreRangéeId"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CodeBarreRangéeRangéeId")
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreRangée_RangéeId")
                        .HasComment("Référence à l'identifiant de la rangée avec ce code-barres est situé. C'est une clé étrangère.");

                    b.HasKey("CodeBarreRangéeId")
                        .HasName("PK__CodeBarr__47535DFE57D2BBF1");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("CodeBarreRangéeRangéeId");

                    b.ToTable("CodeBarreRangée", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreZone", b =>
                {
                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("CodeBarreZone_ZoneId")
                        .HasComment("Référence à l'identifiant de la zone avec ce code-barres est situé. C'est une clé étrangère.");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CodeBarreZoneZoneId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ZoneNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneSiteId")
                        .HasColumnType("int");

                    b.HasKey("ZoneId")
                        .HasName("PK__CodeBarr__F046EBC6C1681EC7");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CodeBarreZoneZoneId");

                    b.HasIndex("ZoneSiteId");

                    b.ToTable("CodeBarreZone", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Equipe", b =>
                {
                    b.Property<int>("EquipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Equipe_Id")
                        .HasComment("Identifiant unique pour chaque équipe.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipeId"), 1L, 1);

                    b.Property<int?>("EquipeInventaireId")
                        .HasColumnType("int")
                        .HasColumnName("Equipe_InventaireId")
                        .HasComment("Référence à l'identifiant de l'inventaire associé à cette équipe. C'est une clé étrangère qui fait référence à la table Inventaire.");

                    b.Property<string>("EquipeLibelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEquipeArbitrage")
                        .HasColumnType("bit");

                    b.HasKey("EquipeId")
                        .HasName("PK__Equipe__C93C5DE8C09622F5");

                    b.HasIndex("EquipeInventaireId");

                    b.ToTable("Equipe", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EquipeOperateur", b =>
                {
                    b.Property<int>("EquipeOperateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EquipeOperateur_Id")
                        .HasComment("Identifiant unique pour chaque enregistrement dans la relation équipe-opérateur.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipeOperateurId"), 1L, 1);

                    b.Property<int?>("EquipeOperateurEquipeId")
                        .HasColumnType("int")
                        .HasColumnName("EquipeOperateur_EquipeId")
                        .HasComment("Référence à l'identifiant de l'équipe dans laquelle l'opérateur est affecté. C'est une clé étrangère qui fait référence à la table Equipe.");

                    b.Property<int?>("EquipeOperateurOperateurId")
                        .HasColumnType("int")
                        .HasColumnName("EquipeOperateur_OperateurId")
                        .HasComment("Référence à l'identifiant de l'opérateur affecté à l'équipe. C'est une clé étrangère qui fait référence à la table Operateur.");

                    b.HasKey("EquipeOperateurId")
                        .HasName("PK__EquipeOp__CD3D157BD1E82B84");

                    b.HasIndex("EquipeOperateurEquipeId");

                    b.HasIndex("EquipeOperateurOperateurId");

                    b.ToTable("EquipeOperateur", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Etage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Etage_Id")
                        .HasComment("Identifiant unique pour chaque étage");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CodeBarreetageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Etage_Nom")
                        .HasComment("Nom de l'étage");

                    b.Property<int>("RangeeId")
                        .HasColumnType("int")
                        .HasColumnName("Etage_RangéeId")
                        .HasComment("Référence à l'identifiant de la rangée dans laquelle l'étage est situé. C'est une clé étrangère.");

                    b.HasKey("Id")
                        .HasName("PK__Etage__0F13A9CBE9AFC812");

                    b.HasIndex("CodeBarreetageId");

                    b.HasIndex("RangeeId");

                    b.ToTable("Etage", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FormProduit", b =>
                {
                    b.Property<int?>("FormProduitProduitId")
                        .HasColumnType("int")
                        .HasColumnName("FormProduit_ProduitId")
                        .HasComment("Référence à l'identifiant du produit parent. C'est une clé étrangère.");

                    b.Property<string>("CodeBarre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FormProduit_CodeBarre")
                        .HasComment("Code-barres unique pour identifier cette forme spécifique du produit.");

                    b.Property<int?>("FormProduitQuantite")
                        .HasColumnType("int")
                        .HasColumnName("FormProduit_Quantite")
                        .HasComment("Quantité disponible de cette forme du produit.");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int")
                        .HasColumnName("FormProduit_Id")
                        .HasComment("Identifiant unique pour chaque forme de produit");

                    b.HasKey("FormProduitProduitId")
                        .HasName("PK__FormProd__277478DA1E43E773");

                    b.ToTable("FormProduit", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HistoriqueComptage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CommentaireOperateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstAnnulé")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotifModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantitéComptée")
                        .HasColumnType("int");

                    b.Property<int>("ResultatInventaireId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResultatInventaireId");

                    b.ToTable("HistoriqueComptages");
                });

            modelBuilder.Entity("Domain.Entities.Inventaire", b =>
                {
                    b.Property<int>("InventaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Inventaire_Id")
                        .HasComment("Identifiant unique pour chaque inventaire.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventaireId"), 1L, 1);

                    b.Property<DateTime?>("InventaireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Inventaire_Date")
                        .HasComment("Date de l'inventaire.");

                    b.Property<bool?>("InventaireIsTotal")
                        .HasColumnType("bit")
                        .HasColumnName("Inventaire_IsTotal")
                        .HasComment("Indicateur qui spécifie si l'inventaire est total (1) ou partiel (0).");

                    b.Property<string>("InventaireLibelle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Inventaire_libelle")
                        .HasComment("Libellé ou nom de l'inventaire");

                    b.Property<int?>("InventaireSiteId")
                        .HasColumnType("int")
                        .HasColumnName("Inventaire_SiteId")
                        .HasComment("Référence au site où l'inventaire est effectué, lié à l'identifiant du site dans la table Site.");

                    b.Property<int?>("InventaireStatutId")
                        .HasColumnType("int")
                        .HasColumnName("Inventaire_StatutId")
                        .HasComment("Référence au statut de l'inventaire, lié à l'identifiant du statut dans la table Statut.");

                    b.Property<int?>("InventaireTypeInventaireId")
                        .HasColumnType("int")
                        .HasColumnName("Inventaire_TypeInventaireId")
                        .HasComment("Référence au type d'inventaire, lié à l'identifiant du type dans la table TypeInventaire.");

                    b.Property<string>("MotDePasse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventaireId")
                        .HasName("PK__Inventai__4645A98DF52C4799");

                    b.HasIndex("InventaireSiteId");

                    b.HasIndex("InventaireStatutId");

                    b.HasIndex("InventaireTypeInventaireId");

                    b.ToTable("Inventaire", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Operateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Operateur_Id")
                        .HasComment("Identifiant unique pour chaque opérateur.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Operateur_Nom")
                        .HasComment("Nom de l'opérateur.");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Operateur_Prenom")
                        .HasComment("Prénom de l'opérateur.");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("Operateur_SiteId")
                        .HasComment("Référence à l'identifiant du site où l'opérateur travaille. C'est une clé étrangère qui fait référence à la table Site.");

                    b.Property<int>("SiteId1")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Operateur_AspNetUsersId");

                    b.Property<string>("cin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Operateur_Cin")
                        .HasComment("Numéro de carte d'identité nationale de l'opérateur.");

                    b.HasKey("Id")
                        .HasName("PK__Operateu__DD6FAFB1471872AD");

                    b.HasIndex("SiteId");

                    b.HasIndex("SiteId1");

                    b.HasIndex("UserId");

                    b.ToTable("Operateur", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OperationInventaire", b =>
                {
                    b.Property<int>("OperationInventaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OperationInventaire_Id")
                        .HasComment("Identifiant unique pour chaque opération d'inventaire. ");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationInventaireId"), 1L, 1);

                    b.Property<int?>("CodeBarreZoneZoneId")
                        .HasColumnType("int");

                    b.Property<int?>("OperationInventaireInventaireId")
                        .HasColumnType("int")
                        .HasColumnName("OperationInventaire_InventaireId")
                        .HasComment("Référence à l'identifiant de l'inventaire auquel cette opération appartient. C'est une clé étrangère qui fait référence à la table Inventaire.");

                    b.Property<int>("OperationInventaireStatut")
                        .HasColumnType("int");

                    b.Property<int?>("OperationInventaireZoneId")
                        .HasColumnType("int")
                        .HasColumnName("OperationInventaire_ZoneId")
                        .HasComment("Référence à l'identifiant de la zone dans laquelle l'opération d'inventaire est réalisée. C'est une clé étrangère qui fait référence à la table Zone.");

                    b.HasKey("OperationInventaireId")
                        .HasName("PK__Operatio__18B7EDD044030108");

                    b.HasIndex("CodeBarreZoneZoneId");

                    b.HasIndex("OperationInventaireInventaireId");

                    b.HasIndex("OperationInventaireZoneId");

                    b.ToTable("OperationInventaire", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Produit_Id")
                        .HasComment("Identifiant unique pour chaque produit.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CodeBarreEtageId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Produit_Prix")
                        .HasComment("Prix du produit.");

                    b.Property<int?>("ProduitEtageId")
                        .HasColumnType("int")
                        .HasColumnName("Produit_EtageId")
                        .HasComment("Référence à l'identifiant de l'étage où le produit est stocké. C'est une clé étrangère.");

                    b.Property<int?>("QuantiteEnStock")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Produit__DBDF7B2C20682064");

                    b.HasIndex("CodeBarreEtageId");

                    b.HasIndex("ProduitEtageId");

                    b.ToTable("Produit", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Rack", b =>
                {
                    b.Property<int>("RackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Rack_Id")
                        .HasComment("Identifiant unique pour chaque rack");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RackId"), 1L, 1);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RackAlleeId")
                        .HasColumnType("int")
                        .HasColumnName("Rack_AlleeId")
                        .HasComment("Référence à l'identifiant de l'Allee dans laquelle le rack est situé. C'est une clé étrangère.");

                    b.Property<string>("RackNom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Rack_Nom")
                        .HasComment("Nom du rack");

                    b.HasKey("RackId")
                        .HasName("PK__Rack__3B72075B69B2E97F");

                    b.HasIndex("RackAlleeId");

                    b.ToTable("Rack", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Rangee", b =>
                {
                    b.Property<int>("RangeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Rangée_Id")
                        .HasComment("Identifiant unique pour chaque rangée");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangeeId"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RangeeNom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Rangée_Nom")
                        .HasComment("Nom de la rangée");

                    b.Property<int?>("RangeeRackId")
                        .HasColumnType("int")
                        .HasColumnName("Rangée_RackId")
                        .HasComment("Référence à l'identifiant du rack dans lequel la rangée est située. C'est une clé étrangère");

                    b.HasKey("RangeeId")
                        .HasName("PK__Rangee__13CD194487C697CF");

                    b.HasIndex("RangeeRackId");

                    b.ToTable("Rangee", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Region_Id")
                        .HasComment("Identifiant unique pour chaque région. C'est la clé primaire.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Region_Nom")
                        .HasComment("Nom de la région.");

                    b.HasKey("Id")
                        .HasName("PK__Region__A9EAD4FFE34950BA");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultatInventaire", b =>
                {
                    b.Property<int>("ResultatInventaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResultatInventaire_Id")
                        .HasComment("Identifiant unique pour chaque enregistrement de résultat d'inventaire.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultatInventaireId"), 1L, 1);

                    b.Property<DateTime>("DateComptage")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("QuantiteScannee")
                        .HasColumnType("int");

                    b.Property<int?>("ResultatInventaireEquipeId")
                        .HasColumnType("int")
                        .HasColumnName("ResultatInventaire_EquipeId")
                        .HasComment("Référence à l'identifiant de l'équipe responsable de l'inventaire, liée à la table Equipe.");

                    b.Property<int?>("ResultatInventaireFormProduitId")
                        .HasColumnType("int")
                        .HasColumnName("ResultatInventaire_FormProduitId")
                        .HasComment("Référence à l'identifiant du produit formulé, lié à la table FormProduit.");

                    b.Property<int?>("ResultatInventaireInventaireId")
                        .HasColumnType("int")
                        .HasColumnName("ResultatInventaire_InventaireId")
                        .HasComment("Référence à l'identifiant de l'inventaire, liée à la table Inventaire.");

                    b.Property<int?>("ResultatInventaireOperateurId")
                        .HasColumnType("int")
                        .HasColumnName("ResultatInventaire_OperateurId")
                        .HasComment("Référence à l'identifiant de l'opérateur qui a participé à l'inventaire, liée à la table Operateur.");

                    b.Property<int?>("StockArbitre")
                        .HasColumnType("int");

                    b.Property<int>("ÉtapeComptage")
                        .HasColumnType("int");

                    b.HasKey("ResultatInventaireId")
                        .HasName("PK__Resultat__AABC56D849C78C73");

                    b.HasIndex("FormProduitId");

                    b.HasIndex("ResultatInventaireEquipeId");

                    b.HasIndex("ResultatInventaireFormProduitId");

                    b.HasIndex("ResultatInventaireInventaireId");

                    b.HasIndex("ResultatInventaireOperateurId");

                    b.ToTable("ResultatInventaire", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Site_Id")
                        .HasComment(" Identifiant unique du site");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Site_Adress")
                        .HasComment("Adresse physique du site");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Site_Email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SiteNom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Site_Nom")
                        .HasComment("Nom du site");

                    b.Property<int?>("SiteSocieteId")
                        .HasColumnType("int")
                        .HasColumnName("Site_SocieteId")
                        .HasComment("Identifiant de la société propriétaire du site");

                    b.Property<int?>("SiteTelephone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Site_Telephone");

                    b.Property<int?>("SiteVilleId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("Site_VilleId")
                        .HasComment("Clé étrangère qui fait référence à Ville_Id dans la table Ville, indiquant la ville où se trouve le site.");

                    b.Property<long>("SocieteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Site__E422232E1CD135AA");

                    b.HasIndex("SiteSocieteId");

                    b.HasIndex("SiteVilleId");

                    b.HasIndex(new[] { "Adress" }, "UQ__Site__442E7CDE2D3D21D9")
                        .IsUnique();

                    b.ToTable("Site", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Societe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Societé_Id")
                        .HasComment("Identifiant unique de la société");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Societé_Adress")
                        .HasComment("Adresse de la société");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("Societé_ClientId")
                        .HasComment("Clé étrangère qui fait référence à client_ID dans la table Client, indiquant le client associé à la société.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IF")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Societé_If")
                        .HasComment("Numéro d'identification fiscale de la société");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Societé_Rs")
                        .HasComment("Raison sociale ou nom de la société");

                    b.Property<int?>("SocieteClientId")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Societé_Telephone")
                        .HasComment("Numéro de téléphone de la société");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VilleId")
                        .HasColumnType("int")
                        .HasColumnName("Societé_VilleId")
                        .HasComment("Clé étrangère qui fait référence à la table Ville (par exemple, pour stocker l'ID de la ville où se trouve la société).");

                    b.HasKey("Id")
                        .HasName("PK__Societé__04358C9F3CFB2E8D");

                    b.HasIndex("ClientId");

                    b.HasIndex("VilleId");

                    b.HasIndex(new[] { "Adresse" }, "UQ__Societé__E5F76C6DFED7C7AE")
                        .IsUnique();

                    b.ToTable("Societé", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Statut", b =>
                {
                    b.Property<int>("StatutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Statut_Id")
                        .HasComment("Identifiant unique pour chaque statut.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatutId"), 1L, 1);

                    b.Property<string>("StatutLibelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutNom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Statut_Nom")
                        .HasComment("Nom du statut");

                    b.HasKey("StatutId")
                        .HasName("PK__Statut__C9A2F59F5987DD15");

                    b.ToTable("Statut", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TypeInventaire", b =>
                {
                    b.Property<int>("TypeInventaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TypeInventaire_Id")
                        .HasComment("Identifiant unique pour chaque type d'inventaire.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeInventaireId"), 1L, 1);

                    b.Property<string>("TypeInventaireLibelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TypeInventaire_libelle")
                        .HasComment("Libellé du type d'inventaire (ex: \"Inventaire simple\", \"Inventaire double avec arbitrage\".).");

                    b.HasKey("TypeInventaireId")
                        .HasName("PK__TypeInve__03EB729C10902F8A");

                    b.ToTable("TypeInventaire", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ville", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ville_Id")
                        .HasComment("Identifiant unique pour chaque ville");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Ville_Nom")
                        .HasComment("Nom de la ville");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("Ville_RegionId")
                        .HasComment("Référence à l'identifiant de la région à laquelle appartient la ville.");

                    b.Property<int>("RegionId1")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Ville__5A0D204B8CEEE4A5");

                    b.HasIndex("RegionId");

                    b.HasIndex("RegionId1");

                    b.ToTable("Ville", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Zone_Id")
                        .HasComment("Identifiant unique pour chaque zone.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"), 1L, 1);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ZoneNom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Zone_Nom")
                        .HasComment("Nom de la zone.");

                    b.Property<int?>("ZoneSiteId")
                        .HasColumnType("int")
                        .HasColumnName("Zone_SiteId")
                        .HasComment("Référence à l'identifiant du site auquel appartient la zone. C'est une clé étrangère.");

                    b.HasKey("ZoneId")
                        .HasName("PK__Zone__B4610C9EE22380FB");

                    b.HasIndex("ZoneSiteId");

                    b.ToTable("Zone", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("IdentityUserRole<string>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Admin", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Allee", b =>
                {
                    b.HasOne("Domain.Entities.Zone", "AlleeZone")
                        .WithMany("Allee")
                        .HasForeignKey("AlleeZoneId")
                        .HasConstraintName("Allee_ZoneId");

                    b.HasOne("Domain.Entities.CodeBarreZone", null)
                        .WithMany("Allees")
                        .HasForeignKey("CodeBarreZoneZoneId");

                    b.Navigation("AlleeZone");
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreAllee", b =>
                {
                    b.HasOne("Domain.Entities.Allee", "CodeBarreAlleeAllee")
                        .WithMany("CodeBarreAllee")
                        .HasForeignKey("CodeBarreAlleeAlleeId")
                        .HasConstraintName("CodeBarreAllee_AlleeId");

                    b.Navigation("CodeBarreAlleeAllee");
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreEtage", b =>
                {
                    b.HasOne("Domain.Entities.Etage", "CodeBarreEtageEtage")
                        .WithMany("CodeBarreEtages")
                        .HasForeignKey("CodeBarreEtageEtageId")
                        .HasConstraintName("CodeBarreEtage_EtageId");

                    b.Navigation("CodeBarreEtageEtage");
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreOperateur", b =>
                {
                    b.HasOne("Domain.Entities.Operateur", "CodeBarreOperateurOperateur")
                        .WithMany("CodeBarreOperateurs")
                        .HasForeignKey("CodeBarreOperateurOperateurId")
                        .HasConstraintName("CodeBarreOperateur_OperateurId");

                    b.HasOne("Domain.Entities.Site", null)
                        .WithMany("CodeBarreOperateurs")
                        .HasForeignKey("SiteId");

                    b.Navigation("CodeBarreOperateurOperateur");
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreRack", b =>
                {
                    b.HasOne("Domain.Entities.Rack", "CodeBarreRackRack")
                        .WithMany("CodeBarreRacks")
                        .HasForeignKey("CodeBarreRackRackId")
                        .HasConstraintName("CodeBarreRack_RackId");

                    b.Navigation("CodeBarreRackRack");
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreRangee", b =>
                {
                    b.HasOne("Domain.Entities.Rangee", "CodeBarreRangéeRangée")
                        .WithMany("CodeBarreRangees")
                        .HasForeignKey("CodeBarreRangéeRangéeId")
                        .HasConstraintName("CodeBarreRangée_RangéeId");

                    b.Navigation("CodeBarreRangéeRangée");
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreZone", b =>
                {
                    b.HasOne("Domain.Entities.CodeBarreZone", null)
                        .WithMany("CodeBarreZones")
                        .HasForeignKey("CodeBarreZoneZoneId");

                    b.HasOne("Domain.Entities.Zone", "CodeBarreZoneZone")
                        .WithMany("CodeBarreZones")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CodeBarreZone_ZoneId");

                    b.HasOne("Domain.Entities.Site", "ZoneSite")
                        .WithMany()
                        .HasForeignKey("ZoneSiteId");

                    b.Navigation("CodeBarreZoneZone");

                    b.Navigation("ZoneSite");
                });

            modelBuilder.Entity("Domain.Entities.Equipe", b =>
                {
                    b.HasOne("Domain.Entities.Inventaire", "EquipeInventaire")
                        .WithMany("Equipes")
                        .HasForeignKey("EquipeInventaireId")
                        .HasConstraintName("Equipe_InventaireId");

                    b.Navigation("EquipeInventaire");
                });

            modelBuilder.Entity("Domain.Entities.EquipeOperateur", b =>
                {
                    b.HasOne("Domain.Entities.Equipe", "EquipeOperateurEquipe")
                        .WithMany("EquipeOperateurs")
                        .HasForeignKey("EquipeOperateurEquipeId")
                        .HasConstraintName("EquipeOperateur_EquipeId");

                    b.HasOne("Domain.Entities.Operateur", "EquipeOperateurOperateur")
                        .WithMany("EquipeOperateurs")
                        .HasForeignKey("EquipeOperateurOperateurId")
                        .HasConstraintName("EquipeOperateur_OperateurId");

                    b.Navigation("EquipeOperateurEquipe");

                    b.Navigation("EquipeOperateurOperateur");
                });

            modelBuilder.Entity("Domain.Entities.Etage", b =>
                {
                    b.HasOne("Domain.Entities.CodeBarreEtage", "CodeBarreetage")
                        .WithMany()
                        .HasForeignKey("CodeBarreetageId");

                    b.HasOne("Domain.Entities.Rangee", "EtageRangee")
                        .WithMany("Etages")
                        .HasForeignKey("RangeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Etage_RangéeId");

                    b.Navigation("CodeBarreetage");

                    b.Navigation("EtageRangee");
                });

            modelBuilder.Entity("Domain.Entities.FormProduit", b =>
                {
                    b.HasOne("Domain.Entities.Produit", "FormProduitProduit")
                        .WithMany("FormProduits")
                        .HasForeignKey("FormProduitProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FormProduit_ProduitId");

                    b.Navigation("FormProduitProduit");
                });

            modelBuilder.Entity("Domain.Entities.HistoriqueComptage", b =>
                {
                    b.HasOne("Domain.Entities.ResultatInventaire", "Resultat")
                        .WithMany()
                        .HasForeignKey("ResultatInventaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resultat");
                });

            modelBuilder.Entity("Domain.Entities.Inventaire", b =>
                {
                    b.HasOne("Domain.Entities.Site", "InventaireSite")
                        .WithMany("Inventaires")
                        .HasForeignKey("InventaireSiteId")
                        .HasConstraintName("Inventaire_SiteId");

                    b.HasOne("Domain.Entities.Statut", "InventaireStatut")
                        .WithMany("Inventaires")
                        .HasForeignKey("InventaireStatutId")
                        .HasConstraintName("Inventaire_StatutId");

                    b.HasOne("Domain.Entities.TypeInventaire", "InventaireTypeInventaire")
                        .WithMany("Inventaires")
                        .HasForeignKey("InventaireTypeInventaireId")
                        .HasConstraintName("Inventaire_TypeInventaireId");

                    b.Navigation("InventaireSite");

                    b.Navigation("InventaireStatut");

                    b.Navigation("InventaireTypeInventaire");
                });

            modelBuilder.Entity("Domain.Entities.Operateur", b =>
                {
                    b.HasOne("Domain.Entities.Site", "OperateurSite")
                        .WithMany("Operateurs")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Operateur_SiteId");

                    b.HasOne("Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Operateurs")
                        .HasForeignKey("UserId");

                    b.Navigation("OperateurSite");

                    b.Navigation("Site");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OperationInventaire", b =>
                {
                    b.HasOne("Domain.Entities.CodeBarreZone", null)
                        .WithMany("OperationInventaires")
                        .HasForeignKey("CodeBarreZoneZoneId");

                    b.HasOne("Domain.Entities.Inventaire", "OperationInventaireInventaire")
                        .WithMany("OperationInventaires")
                        .HasForeignKey("OperationInventaireInventaireId")
                        .HasConstraintName("OperationInventaire_InventaireId");

                    b.HasOne("Domain.Entities.Zone", "OperationInventaireZone")
                        .WithMany("OperationInventaires")
                        .HasForeignKey("OperationInventaireZoneId")
                        .HasConstraintName("OperationInventaire_ZoneId");

                    b.Navigation("OperationInventaireInventaire");

                    b.Navigation("OperationInventaireZone");
                });

            modelBuilder.Entity("Domain.Entities.Produit", b =>
                {
                    b.HasOne("Domain.Entities.CodeBarreEtage", "CodeBarreEtage")
                        .WithMany()
                        .HasForeignKey("CodeBarreEtageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Etage", "ProduitEtage")
                        .WithMany("Produits")
                        .HasForeignKey("ProduitEtageId")
                        .HasConstraintName("Produit_EtageId");

                    b.Navigation("CodeBarreEtage");

                    b.Navigation("ProduitEtage");
                });

            modelBuilder.Entity("Domain.Entities.Rack", b =>
                {
                    b.HasOne("Domain.Entities.Allee", "RackAllee")
                        .WithMany("Racks")
                        .HasForeignKey("RackAlleeId")
                        .HasConstraintName("Rack_AlleeId");

                    b.Navigation("RackAllee");
                });

            modelBuilder.Entity("Domain.Entities.Rangee", b =>
                {
                    b.HasOne("Domain.Entities.Rack", "RangeeRack")
                        .WithMany("Rangées")
                        .HasForeignKey("RangeeRackId")
                        .HasConstraintName("Rangée_RackId");

                    b.Navigation("RangeeRack");
                });

            modelBuilder.Entity("Domain.Entities.ResultatInventaire", b =>
                {
                    b.HasOne("Domain.Entities.FormProduit", "FormProduit")
                        .WithMany()
                        .HasForeignKey("FormProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Equipe", "ResultatInventaireEquipe")
                        .WithMany("ResultatInventaires")
                        .HasForeignKey("ResultatInventaireEquipeId")
                        .HasConstraintName("ResultatInventaire_EquipeId");

                    b.HasOne("Domain.Entities.FormProduit", "ResultatInventaireFormProduit")
                        .WithMany("ResultatInventaires")
                        .HasForeignKey("ResultatInventaireFormProduitId")
                        .HasConstraintName("ResultatInventaire_FormProduitId");

                    b.HasOne("Domain.Entities.Inventaire", "ResultatInventaireInventaire")
                        .WithMany("ResultatInventaires")
                        .HasForeignKey("ResultatInventaireInventaireId")
                        .HasConstraintName("ResultatInventaire_InventaireId");

                    b.HasOne("Domain.Entities.Operateur", "ResultatInventaireOperateur")
                        .WithMany("ResultatInventaires")
                        .HasForeignKey("ResultatInventaireOperateurId")
                        .HasConstraintName("ResultatInventaire_OperateurId");

                    b.Navigation("FormProduit");

                    b.Navigation("ResultatInventaireEquipe");

                    b.Navigation("ResultatInventaireFormProduit");

                    b.Navigation("ResultatInventaireInventaire");

                    b.Navigation("ResultatInventaireOperateur");
                });

            modelBuilder.Entity("Domain.Entities.Site", b =>
                {
                    b.HasOne("Domain.Entities.Societe", "Societe")
                        .WithMany("Sites")
                        .HasForeignKey("SiteSocieteId")
                        .HasConstraintName("Site_SocieteId");

                    b.HasOne("Domain.Entities.Ville", "SiteVille")
                        .WithMany("Sites")
                        .HasForeignKey("SiteVilleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Site_VilleId");

                    b.Navigation("SiteVille");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("Domain.Entities.Societe", b =>
                {
                    b.HasOne("Domain.Entities.Client", "SocietéClient")
                        .WithMany("Societés")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Societé_ClientId");

                    b.HasOne("Domain.Entities.Ville", "SocietéVille")
                        .WithMany("Societés")
                        .HasForeignKey("VilleId")
                        .HasConstraintName("Societé_VilleId");

                    b.Navigation("SocietéClient");

                    b.Navigation("SocietéVille");
                });

            modelBuilder.Entity("Domain.Entities.Ville", b =>
                {
                    b.HasOne("Domain.Entities.Region", "VilleRegion")
                        .WithMany("Villes")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Ville_RegionId");

                    b.HasOne("Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("VilleRegion");
                });

            modelBuilder.Entity("Domain.Entities.Zone", b =>
                {
                    b.HasOne("Domain.Entities.Site", "ZoneSite")
                        .WithMany("Zones")
                        .HasForeignKey("ZoneSiteId")
                        .HasConstraintName("Zone_SiteId");

                    b.Navigation("ZoneSite");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.UserRole", "UserId", "RoleId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Allee", b =>
                {
                    b.Navigation("CodeBarreAllee");

                    b.Navigation("Racks");
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Navigation("Societés");
                });

            modelBuilder.Entity("Domain.Entities.CodeBarreZone", b =>
                {
                    b.Navigation("Allees");

                    b.Navigation("CodeBarreZones");

                    b.Navigation("OperationInventaires");
                });

            modelBuilder.Entity("Domain.Entities.Equipe", b =>
                {
                    b.Navigation("EquipeOperateurs");

                    b.Navigation("ResultatInventaires");
                });

            modelBuilder.Entity("Domain.Entities.Etage", b =>
                {
                    b.Navigation("CodeBarreEtages");

                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Domain.Entities.FormProduit", b =>
                {
                    b.Navigation("ResultatInventaires");
                });

            modelBuilder.Entity("Domain.Entities.Inventaire", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("OperationInventaires");

                    b.Navigation("ResultatInventaires");
                });

            modelBuilder.Entity("Domain.Entities.Operateur", b =>
                {
                    b.Navigation("CodeBarreOperateurs");

                    b.Navigation("EquipeOperateurs");

                    b.Navigation("ResultatInventaires");
                });

            modelBuilder.Entity("Domain.Entities.Produit", b =>
                {
                    b.Navigation("FormProduits");
                });

            modelBuilder.Entity("Domain.Entities.Rack", b =>
                {
                    b.Navigation("CodeBarreRacks");

                    b.Navigation("Rangées");
                });

            modelBuilder.Entity("Domain.Entities.Rangee", b =>
                {
                    b.Navigation("CodeBarreRangees");

                    b.Navigation("Etages");
                });

            modelBuilder.Entity("Domain.Entities.Region", b =>
                {
                    b.Navigation("Villes");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Site", b =>
                {
                    b.Navigation("CodeBarreOperateurs");

                    b.Navigation("Inventaires");

                    b.Navigation("Operateurs");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Domain.Entities.Societe", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("Domain.Entities.Statut", b =>
                {
                    b.Navigation("Inventaires");
                });

            modelBuilder.Entity("Domain.Entities.TypeInventaire", b =>
                {
                    b.Navigation("Inventaires");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Operateurs");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Ville", b =>
                {
                    b.Navigation("Sites");

                    b.Navigation("Societés");
                });

            modelBuilder.Entity("Domain.Entities.Zone", b =>
                {
                    b.Navigation("Allee");

                    b.Navigation("CodeBarreZones");

                    b.Navigation("OperationInventaires");
                });
#pragma warning restore 612, 618
        }
    }
}
